### ISSUE TITLE
Gradle task convertSwagger2markup is "UP-TO-DATE" after gradle clean

### ISSUE THREAD

**Issue by seprich** [RobWin/swagger2markup-gradle-plugin#7]
1st `gradle task convertSwagger2markup`
2nd `gradle clean`
3rd `gradle task convertSwagger2markup`
And this time does nothing because ":convertSwagger2markup UP-TO-DATE"
Seems to be a bug in this plugin

This happens with following configuration:
```
convertSwagger2markup {
    swaggerInput file("src/main/resources/schemas/sync.yaml").getAbsolutePath()
    outputFile file("${buildDir}/asciidoc/sync")
    config = ['swagger2markup.markupLanguage' : 'ASCIIDOC',
              'swagger2markup.pathsGroupedBy': 'AS_IS',
              'swagger2markup.interDocumentCrossReferencesEnabled': true]
}
```

Not sure if the outputFile (vs the more usual outputDir) brings this effect..
To get over this problem i had to add a `outputs.upToDateWhen { false }` instruction to the task - a hack for sure but had to do something.

**Comment by cleydsonjr** [comment]
+1

**Comment by atomfrede** [comment]
I think it is because gradle checks if any inputs to a task have changed. In this case the input is the path of the swagger yaml. The path never changes, only the content of the file. So I would propose to have the task always be out of date or try to use the yaml file as input such that gradle can check if the content has changed. Can also provide a PR if needed.

**Comment by atomfrede** [comment]
EDIT: I couln't reproduce it with the default example you can find here: https://github.com/Swagger2Markup/swagger2markup-gradle-project-template So maybe this can be closed

![bildschirmfoto-20170930130533-1920x1054](https://user-images.githubusercontent.com/203401/31045294-9a075486-a5e0-11e7-8474-a3e324943021.png)

**Comment by wakingrufus** [comment]
I also have this problem. to reproduce, perhaps try running 
```gradle taskThatCreatesASwaggerJson```
```gradle convertSwagger2markup```
*** make a change that would cause the swagger.json to be different ***
```gradle taskThatCreatesASwaggerJson```
```gradle convertSwagger2markup```

**Comment by wakingrufus** [comment]
I was able to reproduce this in a test in my branch here: https://github.com/wakingrufus/swagger2markup-gradle-plugin/tree/detect-input-changes

**Comment by wakingrufus** [comment]
I also committed a fix for the issue, by adding a new "swaggerInputFile" property

**Comment by lhotari** [comment]
@RobWin  Is there a schedule for the next release that would contain this fix?

**Comment by lhotari** [comment]
FYI, I released a fork of this plugin since I really badly needed this fix: https://plugins.gradle.org/plugin/io.github.lhotari.swagger2markup .
