### ISSUE TITLE
Release version 1.3.2 of Gradle plugin

### ISSUE THREAD

**Issue by dmart77** [RobWin/swagger2markup-gradle-plugin#8]
Please make a release 1.3.2 if possible. Would like to get latest fixes.

**Comment by RobWin** [comment]
I hope I have some time soon.
But you can (almost) always use the latest version of Swagger2Markup without a new Plugin version.
See here: https://github.com/Swagger2Markup/swagger2markup-gradle-project-template/blob/master/build.gradle#L11
You can just update it to 1.3.2.

**Comment by RobWin** [comment]
Thx for using Swagger2Markup. We would love to get your GitHub Star in the root project :)

**Comment by dmart77** [comment]
It works, Thank you.
